hidden_layers: 'hidden_layers' # path to hidden layers with test/train/val split inside this folder
type: 'ligand' # ligand, receptor, or both: which graph/model will you use
batch_size: 100 # batch size for training only
model_output: 'runs/score/ligand_trained.pt' # path to save model